"""empty message

Revision ID: 2462be349b58
Revises: 25bc2d59107a
Create Date: 2014-12-22 18:09:37.613000

"""

# revision identifiers, used by Alembic.
revision = '2462be349b58'
down_revision = '25bc2d59107a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
