"""empty message

Revision ID: 280d56fda648
Revises: 2462be349b58
Create Date: 2015-01-05 14:07:55.173000

"""

# revision identifiers, used by Alembic.
revision = '280d56fda648'
down_revision = '2462be349b58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
