"""empty message

Revision ID: 28c96df55aab
Revises: 564421848661
Create Date: 2014-11-27 17:35:22.638000

"""

# revision identifiers, used by Alembic.
revision = '28c96df55aab'
down_revision = '564421848661'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
