"""empty message

Revision ID: 28ce15a3805b
Revises: 29ba62ac7ce0
Create Date: 2014-11-27 14:44:19.946000

"""

# revision identifiers, used by Alembic.
revision = '28ce15a3805b'
down_revision = '29ba62ac7ce0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
