"""empty message

Revision ID: 2dfb6eb514ca
Revises: 280d56fda648
Create Date: 2015-01-05 14:21:39.683000

"""

# revision identifiers, used by Alembic.
revision = '2dfb6eb514ca'
down_revision = '280d56fda648'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
