"""empty message

Revision ID: 44c955cc25c8
Revises: 1748e99e387b
Create Date: 2014-12-10 13:08:26.626000

"""

# revision identifiers, used by Alembic.
revision = '44c955cc25c8'
down_revision = '1748e99e387b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    op.add_column('users', sa.Column('filename', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'filename')
    op.create_table('upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
