"""empty message

Revision ID: e427290e50d
Revises: 4efa53b97b2c
Create Date: 2014-12-22 17:03:12.271000

"""

# revision identifiers, used by Alembic.
revision = 'e427290e50d'
down_revision = '4efa53b97b2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_date'), 'files', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_date'), table_name='files')
    op.drop_table('files')
    ### end Alembic commands ###
