"""empty message

Revision ID: 134effd1790d
Revises: 3a9932c5f5a5
Create Date: 2015-01-28 13:03:08.738000

"""

# revision identifiers, used by Alembic.
revision = '134effd1790d'
down_revision = '3a9932c5f5a5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Payslip_date'), 'Payslip', ['date'], unique=False)
    op.drop_table('files')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_Payslip_date'), table_name='Payslip')
    op.drop_table('Payslip')
    ### end Alembic commands ###
