"""Added a PickleType to add dictionaries in leave dates

Revision ID: 195c146db402
Revises: 44d743c65b77
Create Date: 2015-02-09 17:58:00.614000

"""

# revision identifiers, used by Alembic.
revision = '195c146db402'
down_revision = '44d743c65b77'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
