"""Renamed filebase table to payslip table

Revision ID: 1efff8586020
Revises: 134effd1790d
Create Date: 2015-01-28 13:04:42.938000

"""

# revision identifiers, used by Alembic.
revision = '1efff8586020'
down_revision = '134effd1790d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
