"""Added record for appliead and decided dates

Revision ID: 2d2d6ca3b27b
Revises: 549baaa531b4
Create Date: 2015-02-18 11:14:05.952000

"""

# revision identifiers, used by Alembic.
revision = '2d2d6ca3b27b'
down_revision = '549baaa531b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userstatistics', sa.Column('offsetDatesAppliedDates', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('offsetDatesDecidedDates', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('slDatesAppliedDates', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('slDatesDecidedDates', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('vlDatesAppliedDates', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('vlDatesDecidedDates', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstatistics', 'vlDatesDecidedDates')
    op.drop_column('userstatistics', 'vlDatesAppliedDates')
    op.drop_column('userstatistics', 'slDatesDecidedDates')
    op.drop_column('userstatistics', 'slDatesAppliedDates')
    op.drop_column('userstatistics', 'offsetDatesDecidedDates')
    op.drop_column('userstatistics', 'offsetDatesAppliedDates')
    ### end Alembic commands ###
