"""Added supervisor and supervisee attribs

Revision ID: 3190eb2df6a3
Revises: 3a3ca4bc0b2f
Create Date: 2015-02-12 20:53:10.899000

"""

# revision identifiers, used by Alembic.
revision = '3190eb2df6a3'
down_revision = '3a3ca4bc0b2f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
