"""added proposed offset

Revision ID: 3d91a2a86b6f
Revises: 50fff655653c
Create Date: 2015-02-20 17:19:22.039000

"""

# revision identifiers, used by Alembic.
revision = '3d91a2a86b6f'
down_revision = '50fff655653c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userstatistics', sa.Column('proposed_offset', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstatistics', 'proposed_offset')
    ### end Alembic commands ###
