"""Added active roles

Revision ID: 40b970c1d72e
Revises: 73b35ad774e
Create Date: 2015-02-04 17:03:14.459000

"""

# revision identifiers, used by Alembic.
revision = '40b970c1d72e'
down_revision = '73b35ad774e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_role', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_role')
    ### end Alembic commands ###
