"""Added record attribute for dates

Revision ID: 459c299f1a8e
Revises: 3190eb2df6a3
Create Date: 2015-02-17 17:15:55.702000

"""

# revision identifiers, used by Alembic.
revision = '459c299f1a8e'
down_revision = '3190eb2df6a3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userstatistics', sa.Column('offsetDatesRecord', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('slDatesRecord', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('vlDatesRecord', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstatistics', 'vlDatesRecord')
    op.drop_column('userstatistics', 'slDatesRecord')
    op.drop_column('userstatistics', 'offsetDatesRecord')
    ### end Alembic commands ###
