"""Added cancelled dates in db

Revision ID: 549baaa531b4
Revises: 459c299f1a8e
Create Date: 2015-02-17 18:47:19.579000

"""

# revision identifiers, used by Alembic.
revision = '549baaa531b4'
down_revision = '459c299f1a8e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userstatistics', sa.Column('offestDatesCancelled', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('slDatesCancelled', sa.PickleType(), nullable=True))
    op.add_column('userstatistics', sa.Column('vlDatesCancelled', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userstatistics', 'vlDatesCancelled')
    op.drop_column('userstatistics', 'slDatesCancelled')
    op.drop_column('userstatistics', 'offestDatesCancelled')
    ### end Alembic commands ###
