"""empty message

Revision ID: 1748e99e387b
Revises: 2a2a46f7cf6a
Create Date: 2014-12-01 13:32:42.294000

"""

# revision identifiers, used by Alembic.
revision = '1748e99e387b'
down_revision = '2a2a46f7cf6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    ### end Alembic commands ###
