"""empty message

Revision ID: 1cb220051612
Revises: 3f0c0a6c1b0f
Create Date: 2014-11-27 11:18:45.121000

"""

# revision identifiers, used by Alembic.
revision = '1cb220051612'
down_revision = '3f0c0a6c1b0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
