"""empty message

Revision ID: 25bc2d59107a
Revises: e427290e50d
Create Date: 2014-12-22 17:25:50.327000

"""

# revision identifiers, used by Alembic.
revision = '25bc2d59107a'
down_revision = 'e427290e50d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
