"""empty message

Revision ID: 2a2a46f7cf6a
Revises: 19cd3eb8e78a
Create Date: 2014-12-01 10:57:38.413000

"""

# revision identifiers, used by Alembic.
revision = '2a2a46f7cf6a'
down_revision = '19cd3eb8e78a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
