"""empty message

Revision ID: 32017bf4c688
Revises: 597cb641d7bb
Create Date: 2015-01-05 15:08:57.064000

"""

# revision identifiers, used by Alembic.
revision = '32017bf4c688'
down_revision = '597cb641d7bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
