"""empty message

Revision ID: 424d03599dda
Revises: 28c96df55aab
Create Date: 2014-11-27 17:44:05.719000

"""

# revision identifiers, used by Alembic.
revision = '424d03599dda'
down_revision = '28c96df55aab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
