"""empty message

Revision ID: 4efa53b97b2c
Revises: 44c955cc25c8
Create Date: 2014-12-10 14:14:22.074000

"""

# revision identifiers, used by Alembic.
revision = '4efa53b97b2c'
down_revision = '44c955cc25c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    ### end Alembic commands ###
