"""empty message

Revision ID: 564421848661
Revises: 28ce15a3805b
Create Date: 2014-11-27 15:32:12.785000

"""

# revision identifiers, used by Alembic.
revision = '564421848661'
down_revision = '28ce15a3805b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
