"""empty message

Revision ID: dc793b4e347
Revises: 427ddf3aa2fc
Create Date: 2014-11-24 11:40:11.965000

"""

# revision identifiers, used by Alembic.
revision = 'dc793b4e347'
down_revision = '427ddf3aa2fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
